// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: bugly.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuglyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssueId          string `protobuf:"bytes,1,opt,name=issueId,proto3" json:"issueId,omitempty"`                   // 问题 Id
	ErrorType        string `protobuf:"bytes,2,opt,name=errorType,proto3" json:"errorType,omitempty"`               // 错误类型
	AppVersion       string `protobuf:"bytes,3,opt,name=appVersion,proto3" json:"appVersion,omitempty"`             // 软件版本
	AppName          string `protobuf:"bytes,4,opt,name=appName,proto3" json:"appName,omitempty"`                   // 产品名称
	CrashTimes       string `protobuf:"bytes,5,opt,name=crashTimes,proto3" json:"crashTimes,omitempty"`             // 异常次数
	CrashDeviceNum   string `protobuf:"bytes,6,opt,name=crashDeviceNum,proto3" json:"crashDeviceNum,omitempty"`     // 异常设备数量
	StackFlag        string `protobuf:"bytes,7,opt,name=stackFlag,proto3" json:"stackFlag,omitempty"`               // 堆栈特征
	CrashDescription string `protobuf:"bytes,8,opt,name=crashDescription,proto3" json:"crashDescription,omitempty"` // crash 描述
	LastCrashTime    string `protobuf:"bytes,9,opt,name=lastCrashTime,proto3" json:"lastCrashTime,omitempty"`       // 最后一次 crash 时间
	Status           string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`                    // 处理状态
	ProcessPerson    string `protobuf:"bytes,11,opt,name=processPerson,proto3" json:"processPerson,omitempty"`      // 处理人
}

func (x *BuglyInfo) Reset() {
	*x = BuglyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuglyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuglyInfo) ProtoMessage() {}

func (x *BuglyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuglyInfo.ProtoReflect.Descriptor instead.
func (*BuglyInfo) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{0}
}

func (x *BuglyInfo) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *BuglyInfo) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *BuglyInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *BuglyInfo) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *BuglyInfo) GetCrashTimes() string {
	if x != nil {
		return x.CrashTimes
	}
	return ""
}

func (x *BuglyInfo) GetCrashDeviceNum() string {
	if x != nil {
		return x.CrashDeviceNum
	}
	return ""
}

func (x *BuglyInfo) GetStackFlag() string {
	if x != nil {
		return x.StackFlag
	}
	return ""
}

func (x *BuglyInfo) GetCrashDescription() string {
	if x != nil {
		return x.CrashDescription
	}
	return ""
}

func (x *BuglyInfo) GetLastCrashTime() string {
	if x != nil {
		return x.LastCrashTime
	}
	return ""
}

func (x *BuglyInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BuglyInfo) GetProcessPerson() string {
	if x != nil {
		return x.ProcessPerson
	}
	return ""
}

type BugylDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrashHash       string `protobuf:"bytes,1,opt,name=crashHash,proto3" json:"crashHash,omitempty"`              // crashHash
	IssueId         string `protobuf:"bytes,2,opt,name=issueId,proto3" json:"issueId,omitempty"`                  // issueId
	CrashId         string `protobuf:"bytes,3,opt,name=crashId,proto3" json:"crashId,omitempty"`                  // crashId
	UserId          string `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`                    // 用户ID
	DeviceId        string `protobuf:"bytes,5,opt,name=deviceId,proto3" json:"deviceId,omitempty"`                // 设备ID
	UploadTime      string `protobuf:"bytes,6,opt,name=uploadTime,proto3" json:"uploadTime,omitempty"`            // 上报时间
	CrashTime       string `protobuf:"bytes,7,opt,name=crashTime,proto3" json:"crashTime,omitempty"`              // 发生时间
	AppBundleId     string `protobuf:"bytes,8,opt,name=appBundleId,proto3" json:"appBundleId,omitempty"`          // 应用包名
	AppVersion      string `protobuf:"bytes,9,opt,name=appVersion,proto3" json:"appVersion,omitempty"`            // 应用版本
	DeviceModel     string `protobuf:"bytes,10,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`         // 设备机型
	SystemVersion   string `protobuf:"bytes,11,opt,name=systemVersion,proto3" json:"systemVersion,omitempty"`     // 系统版本
	RomDetail       string `protobuf:"bytes,12,opt,name=romDetail,proto3" json:"romDetail,omitempty"`             // ROM详情
	CpuArchitecture string `protobuf:"bytes,13,opt,name=cpuArchitecture,proto3" json:"cpuArchitecture,omitempty"` // CPU架构
	IsJump          string `protobuf:"bytes,14,opt,name=isJump,proto3" json:"isJump,omitempty"`                   // 是否越狱
	MemorySize      string `protobuf:"bytes,15,opt,name=memorySize,proto3" json:"memorySize,omitempty"`           // 可用内存大小
	StoreSizse      string `protobuf:"bytes,16,opt,name=storeSizse,proto3" json:"storeSizse,omitempty"`           // 可用存储空间
	SdSizse         string `protobuf:"bytes,17,opt,name=sdSizse,proto3" json:"sdSizse,omitempty"`                 // 可用SD卡大小
}

func (x *BugylDetail) Reset() {
	*x = BugylDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BugylDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BugylDetail) ProtoMessage() {}

func (x *BugylDetail) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BugylDetail.ProtoReflect.Descriptor instead.
func (*BugylDetail) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{1}
}

func (x *BugylDetail) GetCrashHash() string {
	if x != nil {
		return x.CrashHash
	}
	return ""
}

func (x *BugylDetail) GetIssueId() string {
	if x != nil {
		return x.IssueId
	}
	return ""
}

func (x *BugylDetail) GetCrashId() string {
	if x != nil {
		return x.CrashId
	}
	return ""
}

func (x *BugylDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BugylDetail) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *BugylDetail) GetUploadTime() string {
	if x != nil {
		return x.UploadTime
	}
	return ""
}

func (x *BugylDetail) GetCrashTime() string {
	if x != nil {
		return x.CrashTime
	}
	return ""
}

func (x *BugylDetail) GetAppBundleId() string {
	if x != nil {
		return x.AppBundleId
	}
	return ""
}

func (x *BugylDetail) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *BugylDetail) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *BugylDetail) GetSystemVersion() string {
	if x != nil {
		return x.SystemVersion
	}
	return ""
}

func (x *BugylDetail) GetRomDetail() string {
	if x != nil {
		return x.RomDetail
	}
	return ""
}

func (x *BugylDetail) GetCpuArchitecture() string {
	if x != nil {
		return x.CpuArchitecture
	}
	return ""
}

func (x *BugylDetail) GetIsJump() string {
	if x != nil {
		return x.IsJump
	}
	return ""
}

func (x *BugylDetail) GetMemorySize() string {
	if x != nil {
		return x.MemorySize
	}
	return ""
}

func (x *BugylDetail) GetStoreSizse() string {
	if x != nil {
		return x.StoreSizse
	}
	return ""
}

func (x *BugylDetail) GetSdSizse() string {
	if x != nil {
		return x.SdSizse
	}
	return ""
}

type AppLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile     string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	UserId     string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LogUrl     string `protobuf:"bytes,4,opt,name=log_url,json=logUrl,proto3" json:"log_url,omitempty"`
	Message    string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	CreateTime string `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *AppLogsRequest) Reset() {
	*x = AppLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppLogsRequest) ProtoMessage() {}

func (x *AppLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppLogsRequest.ProtoReflect.Descriptor instead.
func (*AppLogsRequest) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{2}
}

func (x *AppLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppLogsRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AppLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AppLogsRequest) GetLogUrl() string {
	if x != nil {
		return x.LogUrl
	}
	return ""
}

func (x *AppLogsRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppLogsRequest) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type AppLogsInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*AppLogsRequest `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *AppLogsInfo) Reset() {
	*x = AppLogsInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppLogsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppLogsInfo) ProtoMessage() {}

func (x *AppLogsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppLogsInfo.ProtoReflect.Descriptor instead.
func (*AppLogsInfo) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{3}
}

func (x *AppLogsInfo) GetInfos() []*AppLogsRequest {
	if x != nil {
		return x.Infos
	}
	return nil
}

type GetAppLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobles []string `protobuf:"bytes,1,rep,name=mobles,proto3" json:"mobles,omitempty"`
}

func (x *GetAppLogsRequest) Reset() {
	*x = GetAppLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppLogsRequest) ProtoMessage() {}

func (x *GetAppLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppLogsRequest.ProtoReflect.Descriptor instead.
func (*GetAppLogsRequest) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{4}
}

func (x *GetAppLogsRequest) GetMobles() []string {
	if x != nil {
		return x.Mobles
	}
	return nil
}

type BuglyInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*BuglyInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *BuglyInfoRequest) Reset() {
	*x = BuglyInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuglyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuglyInfoRequest) ProtoMessage() {}

func (x *BuglyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuglyInfoRequest.ProtoReflect.Descriptor instead.
func (*BuglyInfoRequest) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{5}
}

func (x *BuglyInfoRequest) GetInfos() []*BuglyInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type BuglyDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*BugylDetail `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *BuglyDetailRequest) Reset() {
	*x = BuglyDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuglyDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuglyDetailRequest) ProtoMessage() {}

func (x *BuglyDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuglyDetailRequest.ProtoReflect.Descriptor instead.
func (*BuglyDetailRequest) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{6}
}

func (x *BuglyDetailRequest) GetInfos() []*BugylDetail {
	if x != nil {
		return x.Infos
	}
	return nil
}

type BuglyDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detals []*BugylDetail `protobuf:"bytes,1,rep,name=detals,proto3" json:"detals,omitempty"`
}

func (x *BuglyDetailResponse) Reset() {
	*x = BuglyDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuglyDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuglyDetailResponse) ProtoMessage() {}

func (x *BuglyDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuglyDetailResponse.ProtoReflect.Descriptor instead.
func (*BuglyDetailResponse) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{7}
}

func (x *BuglyDetailResponse) GetDetals() []*BugylDetail {
	if x != nil {
		return x.Detals
	}
	return nil
}

type BuglyInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*BuglyInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *BuglyInfoResponse) Reset() {
	*x = BuglyInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuglyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuglyInfoResponse) ProtoMessage() {}

func (x *BuglyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuglyInfoResponse.ProtoReflect.Descriptor instead.
func (*BuglyInfoResponse) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{8}
}

func (x *BuglyInfoResponse) GetInfos() []*BuglyInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type BuglyInfoIssueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Versions []string `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
}

func (x *BuglyInfoIssueRequest) Reset() {
	*x = BuglyInfoIssueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuglyInfoIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuglyInfoIssueRequest) ProtoMessage() {}

func (x *BuglyInfoIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuglyInfoIssueRequest.ProtoReflect.Descriptor instead.
func (*BuglyInfoIssueRequest) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{10}
}

func (x *BuglyInfoIssueRequest) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type BuglyDetailIssueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobiles []string `protobuf:"bytes,1,rep,name=mobiles,proto3" json:"mobiles,omitempty"`
}

func (x *BuglyDetailIssueRequest) Reset() {
	*x = BuglyDetailIssueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bugly_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuglyDetailIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuglyDetailIssueRequest) ProtoMessage() {}

func (x *BuglyDetailIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bugly_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuglyDetailIssueRequest.ProtoReflect.Descriptor instead.
func (*BuglyDetailIssueRequest) Descriptor() ([]byte, []int) {
	return file_bugly_proto_rawDescGZIP(), []int{11}
}

func (x *BuglyDetailIssueRequest) GetMobiles() []string {
	if x != nil {
		return x.Mobiles
	}
	return nil
}

var File_bugly_proto protoreflect.FileDescriptor

var file_bugly_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x75, 0x67, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0xf3, 0x02, 0x0a, 0x09, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x61, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x61, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x72, 0x61, 0x73, 0x68, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x72, 0x61, 0x73, 0x68,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x63, 0x6b, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x63, 0x6b, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x72, 0x61, 0x73, 0x68,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x63, 0x72, 0x61, 0x73, 0x68, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x72, 0x61, 0x73, 0x68,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74,
	0x43, 0x72, 0x61, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x95, 0x04, 0x0a, 0x0b, 0x42, 0x75, 0x67, 0x79,
	0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x61, 0x73, 0x68,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x61, 0x73,
	0x68, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x72, 0x61, 0x73, 0x68, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x72, 0x61, 0x73, 0x68, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x72, 0x61, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x61, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61,
	0x70, 0x70, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x70, 0x70, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x24, 0x0a, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x6d, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x70, 0x75, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x70,
	0x75, 0x41, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x73, 0x4a, 0x75, 0x6d, 0x70, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69,
	0x73, 0x4a, 0x75, 0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x69,
	0x7a, 0x73, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x53, 0x69, 0x7a, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x64, 0x53, 0x69, 0x7a, 0x73, 0x65,
	0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x64, 0x53, 0x69, 0x7a, 0x73, 0x65, 0x22,
	0xa5, 0x01, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x4c, 0x6f,
	0x67, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x4c, 0x6f,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73,
	0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x37, 0x0a,
	0x10, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x3b, 0x0a, 0x12, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x05,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x75, 0x67, 0x79, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x69, 0x6e,
	0x66, 0x6f, 0x73, 0x22, 0x3e, 0x0a, 0x13, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x75, 0x67, 0x79, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x6c, 0x73, 0x22, 0x38, 0x0a, 0x11, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x67,
	0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x1e, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x33, 0x0a,
	0x15, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x33, 0x0a, 0x17, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x73, 0x32, 0x80, 0x03, 0x0a, 0x0f, 0x42, 0x75, 0x67, 0x6c,
	0x79, 0x52, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0f, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x70, 0x62, 0x2e, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x75,
	0x67, 0x6c, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x75, 0x67, 0x6c, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x47, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x49, 0x73, 0x73, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x67, 0x6c, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x11, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x12,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x6f, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x4c, 0x6f,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x70, 0x70, 0x4c, 0x6f, 0x67, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bugly_proto_rawDescOnce sync.Once
	file_bugly_proto_rawDescData = file_bugly_proto_rawDesc
)

func file_bugly_proto_rawDescGZIP() []byte {
	file_bugly_proto_rawDescOnce.Do(func() {
		file_bugly_proto_rawDescData = protoimpl.X.CompressGZIP(file_bugly_proto_rawDescData)
	})
	return file_bugly_proto_rawDescData
}

var file_bugly_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_bugly_proto_goTypes = []interface{}{
	(*BuglyInfo)(nil),               // 0: pb.BuglyInfo
	(*BugylDetail)(nil),             // 1: pb.BugylDetail
	(*AppLogsRequest)(nil),          // 2: pb.AppLogsRequest
	(*AppLogsInfo)(nil),             // 3: pb.AppLogsInfo
	(*GetAppLogsRequest)(nil),       // 4: pb.GetAppLogsRequest
	(*BuglyInfoRequest)(nil),        // 5: pb.BuglyInfoRequest
	(*BuglyDetailRequest)(nil),      // 6: pb.BuglyDetailRequest
	(*BuglyDetailResponse)(nil),     // 7: pb.BuglyDetailResponse
	(*BuglyInfoResponse)(nil),       // 8: pb.BuglyInfoResponse
	(*Response)(nil),                // 9: pb.Response
	(*BuglyInfoIssueRequest)(nil),   // 10: pb.BuglyInfoIssueRequest
	(*BuglyDetailIssueRequest)(nil), // 11: pb.BuglyDetailIssueRequest
}
var file_bugly_proto_depIdxs = []int32{
	2,  // 0: pb.AppLogsInfo.infos:type_name -> pb.AppLogsRequest
	0,  // 1: pb.BuglyInfoRequest.infos:type_name -> pb.BuglyInfo
	1,  // 2: pb.BuglyDetailRequest.infos:type_name -> pb.BugylDetail
	1,  // 3: pb.BuglyDetailResponse.detals:type_name -> pb.BugylDetail
	0,  // 4: pb.BuglyInfoResponse.infos:type_name -> pb.BuglyInfo
	5,  // 5: pb.BuglyRpcService.UploadBuglyInfo:input_type -> pb.BuglyInfoRequest
	10, // 6: pb.BuglyRpcService.GetBuglyInfo:input_type -> pb.BuglyInfoIssueRequest
	6,  // 7: pb.BuglyRpcService.UploadBuglyDetails:input_type -> pb.BuglyDetailRequest
	11, // 8: pb.BuglyRpcService.GetBuglyDetails:input_type -> pb.BuglyDetailIssueRequest
	2,  // 9: pb.BuglyRpcService.InsertAppLogInfos:input_type -> pb.AppLogsRequest
	4,  // 10: pb.BuglyRpcService.GetAppLogInfos:input_type -> pb.GetAppLogsRequest
	9,  // 11: pb.BuglyRpcService.UploadBuglyInfo:output_type -> pb.Response
	8,  // 12: pb.BuglyRpcService.GetBuglyInfo:output_type -> pb.BuglyInfoResponse
	9,  // 13: pb.BuglyRpcService.UploadBuglyDetails:output_type -> pb.Response
	7,  // 14: pb.BuglyRpcService.GetBuglyDetails:output_type -> pb.BuglyDetailResponse
	9,  // 15: pb.BuglyRpcService.InsertAppLogInfos:output_type -> pb.Response
	3,  // 16: pb.BuglyRpcService.GetAppLogInfos:output_type -> pb.AppLogsInfo
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_bugly_proto_init() }
func file_bugly_proto_init() {
	if File_bugly_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bugly_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuglyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BugylDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppLogsInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuglyInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuglyDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuglyDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuglyInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuglyInfoIssueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bugly_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuglyDetailIssueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bugly_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bugly_proto_goTypes,
		DependencyIndexes: file_bugly_proto_depIdxs,
		MessageInfos:      file_bugly_proto_msgTypes,
	}.Build()
	File_bugly_proto = out.File
	file_bugly_proto_rawDesc = nil
	file_bugly_proto_goTypes = nil
	file_bugly_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BuglyRpcServiceClient is the client API for BuglyRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuglyRpcServiceClient interface {
	UploadBuglyInfo(ctx context.Context, in *BuglyInfoRequest, opts ...grpc.CallOption) (*Response, error)
	GetBuglyInfo(ctx context.Context, in *BuglyInfoIssueRequest, opts ...grpc.CallOption) (*BuglyInfoResponse, error)
	UploadBuglyDetails(ctx context.Context, in *BuglyDetailRequest, opts ...grpc.CallOption) (*Response, error)
	GetBuglyDetails(ctx context.Context, in *BuglyDetailIssueRequest, opts ...grpc.CallOption) (*BuglyDetailResponse, error)
	InsertAppLogInfos(ctx context.Context, in *AppLogsRequest, opts ...grpc.CallOption) (*Response, error)
	GetAppLogInfos(ctx context.Context, in *GetAppLogsRequest, opts ...grpc.CallOption) (*AppLogsInfo, error)
}

type buglyRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuglyRpcServiceClient(cc grpc.ClientConnInterface) BuglyRpcServiceClient {
	return &buglyRpcServiceClient{cc}
}

func (c *buglyRpcServiceClient) UploadBuglyInfo(ctx context.Context, in *BuglyInfoRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.BuglyRpcService/UploadBuglyInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buglyRpcServiceClient) GetBuglyInfo(ctx context.Context, in *BuglyInfoIssueRequest, opts ...grpc.CallOption) (*BuglyInfoResponse, error) {
	out := new(BuglyInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.BuglyRpcService/GetBuglyInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buglyRpcServiceClient) UploadBuglyDetails(ctx context.Context, in *BuglyDetailRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.BuglyRpcService/UploadBuglyDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buglyRpcServiceClient) GetBuglyDetails(ctx context.Context, in *BuglyDetailIssueRequest, opts ...grpc.CallOption) (*BuglyDetailResponse, error) {
	out := new(BuglyDetailResponse)
	err := c.cc.Invoke(ctx, "/pb.BuglyRpcService/GetBuglyDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buglyRpcServiceClient) InsertAppLogInfos(ctx context.Context, in *AppLogsRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.BuglyRpcService/InsertAppLogInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buglyRpcServiceClient) GetAppLogInfos(ctx context.Context, in *GetAppLogsRequest, opts ...grpc.CallOption) (*AppLogsInfo, error) {
	out := new(AppLogsInfo)
	err := c.cc.Invoke(ctx, "/pb.BuglyRpcService/GetAppLogInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuglyRpcServiceServer is the server API for BuglyRpcService service.
type BuglyRpcServiceServer interface {
	UploadBuglyInfo(context.Context, *BuglyInfoRequest) (*Response, error)
	GetBuglyInfo(context.Context, *BuglyInfoIssueRequest) (*BuglyInfoResponse, error)
	UploadBuglyDetails(context.Context, *BuglyDetailRequest) (*Response, error)
	GetBuglyDetails(context.Context, *BuglyDetailIssueRequest) (*BuglyDetailResponse, error)
	InsertAppLogInfos(context.Context, *AppLogsRequest) (*Response, error)
	GetAppLogInfos(context.Context, *GetAppLogsRequest) (*AppLogsInfo, error)
}

// UnimplementedBuglyRpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBuglyRpcServiceServer struct {
}

func (*UnimplementedBuglyRpcServiceServer) UploadBuglyInfo(context.Context, *BuglyInfoRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBuglyInfo not implemented")
}
func (*UnimplementedBuglyRpcServiceServer) GetBuglyInfo(context.Context, *BuglyInfoIssueRequest) (*BuglyInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuglyInfo not implemented")
}
func (*UnimplementedBuglyRpcServiceServer) UploadBuglyDetails(context.Context, *BuglyDetailRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBuglyDetails not implemented")
}
func (*UnimplementedBuglyRpcServiceServer) GetBuglyDetails(context.Context, *BuglyDetailIssueRequest) (*BuglyDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuglyDetails not implemented")
}
func (*UnimplementedBuglyRpcServiceServer) InsertAppLogInfos(context.Context, *AppLogsRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertAppLogInfos not implemented")
}
func (*UnimplementedBuglyRpcServiceServer) GetAppLogInfos(context.Context, *GetAppLogsRequest) (*AppLogsInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppLogInfos not implemented")
}

func RegisterBuglyRpcServiceServer(s *grpc.Server, srv BuglyRpcServiceServer) {
	s.RegisterService(&_BuglyRpcService_serviceDesc, srv)
}

func _BuglyRpcService_UploadBuglyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuglyInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuglyRpcServiceServer).UploadBuglyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BuglyRpcService/UploadBuglyInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuglyRpcServiceServer).UploadBuglyInfo(ctx, req.(*BuglyInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuglyRpcService_GetBuglyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuglyInfoIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuglyRpcServiceServer).GetBuglyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BuglyRpcService/GetBuglyInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuglyRpcServiceServer).GetBuglyInfo(ctx, req.(*BuglyInfoIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuglyRpcService_UploadBuglyDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuglyDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuglyRpcServiceServer).UploadBuglyDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BuglyRpcService/UploadBuglyDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuglyRpcServiceServer).UploadBuglyDetails(ctx, req.(*BuglyDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuglyRpcService_GetBuglyDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuglyDetailIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuglyRpcServiceServer).GetBuglyDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BuglyRpcService/GetBuglyDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuglyRpcServiceServer).GetBuglyDetails(ctx, req.(*BuglyDetailIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuglyRpcService_InsertAppLogInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuglyRpcServiceServer).InsertAppLogInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BuglyRpcService/InsertAppLogInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuglyRpcServiceServer).InsertAppLogInfos(ctx, req.(*AppLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuglyRpcService_GetAppLogInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuglyRpcServiceServer).GetAppLogInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BuglyRpcService/GetAppLogInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuglyRpcServiceServer).GetAppLogInfos(ctx, req.(*GetAppLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BuglyRpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BuglyRpcService",
	HandlerType: (*BuglyRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadBuglyInfo",
			Handler:    _BuglyRpcService_UploadBuglyInfo_Handler,
		},
		{
			MethodName: "GetBuglyInfo",
			Handler:    _BuglyRpcService_GetBuglyInfo_Handler,
		},
		{
			MethodName: "UploadBuglyDetails",
			Handler:    _BuglyRpcService_UploadBuglyDetails_Handler,
		},
		{
			MethodName: "GetBuglyDetails",
			Handler:    _BuglyRpcService_GetBuglyDetails_Handler,
		},
		{
			MethodName: "InsertAppLogInfos",
			Handler:    _BuglyRpcService_InsertAppLogInfos_Handler,
		},
		{
			MethodName: "GetAppLogInfos",
			Handler:    _BuglyRpcService_GetAppLogInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bugly.proto",
}
